# Fichier: .github/workflows/run-tests.yml (Version finale simplifiée)

name: Python CI - Run Tests and Publish Results

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.6
        ports:
          - 3306:3306
        env:
          MARIADB_ROOT_PASSWORD: supersecretpassword
          MARIADB_DATABASE: analyste_augmente_test

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest and generate report
        env:
          DB_TEST_URL: mysql+pymysql://root:supersecretpassword@127.0.0.1:3306/analyste_augmente_test
        run: pytest -v --junitxml="report.xml"

      - name: Publish results to Xray
        if: success()
        run: python publish_xray_results.py
        env:
          XRAY_CLIENT_ID: ${{ secrets.XRAY_CLIENT_ID }}
          XRAY_CLIENT_SECRET: ${{ secrets.XRAY_CLIENT_SECRET }}